package it.polimi.ingsw.mesos.model.card.character;

import it.polimi.ingsw.mesos.common.enums.CharacterType;
import it.polimi.ingsw.mesos.common.enums.Era;

/**Concrete class for cards of type Builder
 */
public class Builder extends CharacterCard {

    /**Discount on building purchases generated by the builder*/
    private final int discountValue;

    /**Prestige points gained at the end of the game thanks to the builder*/
    private final int prestigePoints;

    /**
     * Constructor for Building Card
     *
     * @param era the era of the card
     * @param playersRequired the number of players required to use the card in the game
     * @param discountValue discount on building purchases generated by the builder
     * @param prestigePoints prestige points gained at the end of the game thanks to the builder
     */
    public Builder(Era era, int playersRequired, int discountValue, int prestigePoints) {
        super(era, playersRequired, CharacterType.BUILDER);
        this.discountValue=discountValue;
        this.prestigePoints=prestigePoints;
    }

    /**
     * Getter method to obtain the discount on buildings
     *
     * @return discount on buildings
     */

    /**Getter method to obtain prestige points at the end of the game
     *
     * @return prestige points at the end of the game
     */
    public int getPrestigePoints() {
        return prestigePoints;
    }

    /**
     * Getter method to obtain the discount on buildings
     *
     * @return discount on buildings
     */
    public int getDiscountValue() {
        return discountValue;
    }
}
